import type { ThemeName, DesignToken } from '@/core/project-schema';

export const DESIGN_TOKENS: Record<ThemeName, DesignToken> = {
  'bram-light': {
    colorPrimary: '#FFFFFF',
    colorSecondary: '#0D5771',
    colorAccent: '#3498E3',
    colorBackground: '#FFFFFF',
    colorSurface: '#F7FAFC',
    colorText: '#1A202C',
    colorTextMuted: '#64748B',
    colorBorder: '#E2E8F0',
    fontHeading: "'Playfair Display', 'Cormorant Garamond', serif",
    fontBody: "'Plus Jakarta Sans', 'Outfit', sans-serif",
    radiusCard: '20px',
    radiusButton: '12px',
    shadowCard: '0 4px 24px rgba(0,0,0,0.06)',
  },
  'apple-luxury': {
    colorPrimary: '#F8FAFC',
    colorSecondary: '#0F172A',
    colorAccent: '#38BDF8',
    colorBackground: '#F8FAFC',
    colorSurface: 'rgba(255,255,255,0.7)',
    colorText: '#0F172A',
    colorTextMuted: '#64748B',
    colorBorder: 'rgba(0,0,0,0.07)',
    fontHeading: "'SF Pro Display', 'Outfit', sans-serif",
    fontBody: "'SF Pro Text', 'Outfit', sans-serif",
    radiusCard: '24px',
    radiusButton: '14px',
    shadowCard: '0 8px 40px rgba(0,0,0,0.08)',
  },
  'dark-obsidian': {
    colorPrimary: '#071A24',
    colorSecondary: '#38BDF8',
    colorAccent: '#F59E0B',
    colorBackground: '#071A24',
    colorSurface: '#0D2A38',
    colorText: '#FFFFFF',
    colorTextMuted: '#94A3B8',
    colorBorder: 'rgba(255,255,255,0.1)',
    fontHeading: "'Space Grotesk', 'Outfit', sans-serif",
    fontBody: "'Plus Jakarta Sans', sans-serif",
    radiusCard: '16px',
    radiusButton: '10px',
    shadowCard: '0 4px 32px rgba(0,0,0,0.4)',
  },
  luxury: {
    colorPrimary: '#1C1917',
    colorSecondary: '#F59E0B',
    colorAccent: '#FEF3C7',
    colorBackground: '#1C1917',
    colorSurface: '#292524',
    colorText: '#FAFAF9',
    colorTextMuted: '#A8A29E',
    colorBorder: 'rgba(255,255,255,0.08)',
    fontHeading: "'Cormorant Garamond', 'Playfair Display', serif",
    fontBody: "'Outfit', sans-serif",
    radiusCard: '16px',
    radiusButton: '8px',
    shadowCard: '0 8px 48px rgba(0,0,0,0.5)',
  },
  editorial: {
    colorPrimary: '#FAFAFA',
    colorSecondary: '#111111',
    colorAccent: '#D97706',
    colorBackground: '#FAFAFA',
    colorSurface: '#F0EEE8',
    colorText: '#111111',
    colorTextMuted: '#6B7280',
    colorBorder: '#D1D5DB',
    fontHeading: "'Playfair Display', 'Cormorant Garamond', serif",
    fontBody: "'Inter', sans-serif",
    radiusCard: '8px',
    radiusButton: '6px',
    shadowCard: '0 2px 16px rgba(0,0,0,0.08)',
  },
  modern: {
    colorPrimary: '#FFFFFF',
    colorSecondary: '#6366F1',
    colorAccent: '#8B5CF6',
    colorBackground: '#FFFFFF',
    colorSurface: '#F5F3FF',
    colorText: '#111827',
    colorTextMuted: '#6B7280',
    colorBorder: '#E5E7EB',
    fontHeading: "'Inter', sans-serif",
    fontBody: "'Inter', sans-serif",
    radiusCard: '16px',
    radiusButton: '10px',
    shadowCard: '0 4px 20px rgba(99,102,241,0.1)',
  },
  minimal: {
    colorPrimary: '#FFFFFF',
    colorSecondary: '#0F172A',
    colorAccent: '#64748B',
    colorBackground: '#FFFFFF',
    colorSurface: '#F8FAFC',
    colorText: '#0F172A',
    colorTextMuted: '#94A3B8',
    colorBorder: '#E2E8F0',
    fontHeading: "'Inter', sans-serif",
    fontBody: "'Inter', sans-serif",
    radiusCard: '12px',
    radiusButton: '8px',
    shadowCard: 'none',
  },
  'google-material': {
    colorPrimary: '#F1F5F9',
    colorSecondary: '#1E293B',
    colorAccent: '#0284C7',
    colorBackground: '#F1F5F9',
    colorSurface: '#FFFFFF',
    colorText: '#1E293B',
    colorTextMuted: '#475569',
    colorBorder: '#CBD5E1',
    fontHeading: "'Google Sans', 'Roboto', sans-serif",
    fontBody: "'Roboto', sans-serif",
    radiusCard: '16px',
    radiusButton: '999px',
    shadowCard: '0 1px 8px rgba(0,0,0,0.12)',
  },
  vibrant: {
    colorPrimary: '#FDF4FF',
    colorSecondary: '#EC4899',
    colorAccent: '#8B5CF6',
    colorBackground: '#FDF4FF',
    colorSurface: '#FFF0FB',
    colorText: '#1A0A1E',
    colorTextMuted: '#9333EA',
    colorBorder: '#F0ABFC',
    fontHeading: "'Outfit', sans-serif",
    fontBody: "'Outfit', sans-serif",
    radiusCard: '24px',
    radiusButton: '999px',
    shadowCard: '0 4px 24px rgba(236,72,153,0.12)',
  },
  'dark-elegance': {
    colorPrimary: '#0B0F17',
    colorSecondary: '#5364F7',
    colorAccent: '#38BDF8',
    colorBackground: '#0B0F17',
    colorSurface: '#131929',
    colorText: '#E2E8F0',
    colorTextMuted: '#64748B',
    colorBorder: 'rgba(255,255,255,0.08)',
    fontHeading: "'Outfit', sans-serif",
    fontBody: "'Outfit', sans-serif",
    radiusCard: '16px',
    radiusButton: '10px',
    shadowCard: '0 8px 40px rgba(0,0,0,0.4)',
  },
};

export function tokensToCSSVars(tokens: DesignToken): string {
  return `
    --color-primary: ${tokens.colorPrimary};
    --color-secondary: ${tokens.colorSecondary};
    --color-accent: ${tokens.colorAccent};
    --color-bg: ${tokens.colorBackground};
    --color-surface: ${tokens.colorSurface};
    --color-text: ${tokens.colorText};
    --color-text-muted: ${tokens.colorTextMuted};
    --color-border: ${tokens.colorBorder};
    --font-heading: ${tokens.fontHeading};
    --font-body: ${tokens.fontBody};
    --radius-card: ${tokens.radiusCard};
    --radius-btn: ${tokens.radiusButton};
    --shadow-card: ${tokens.shadowCard};
  `;
}
